version: '3.3'
services:
  corenlp:
    image: "nlpbox/corenlp:3.9.2"
    ports:
      - "9000:9000"
  dplp-service:
    image: "nlpbox/dplp-service:2021-04-16"
    #    build: . # build locally instead of using image from Docker Hub
    ports:
      - "9001:8000"
    environment:
      - CORENLP_ENDPOINT=http://corenlp:9000
