version: '3.3'
services:
  corenlp:
    image: "nlpbox/corenlp:3.9.1"
    ports:
      - "9000:9000"
  dplp-service:
    build: .
    ports:
      - "9001:8000"
    environment:
      - CORENLP_ENDPOINT=http://corenlp:9000
